#!/usr/bin/env python3
"""Regenerates docs/protocol-vectors.txt: golden FDP/1 frames checked by both
the Swift (mac/Tests) and C (flipper/tests) test suites. The CRC here is an
independent third implementation of CRC-16/CCITT-FALSE."""
import pathlib

def crc16(data: bytes) -> int:
    crc = 0xFFFF
    for b in data:
        crc ^= b << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) if crc & 0x8000 else (crc << 1)
            crc &= 0xFFFF
    return crc

def frame(payload: str) -> str:
    return f"{payload}*{crc16(payload.encode()):04X}"

assert crc16(b"123456789") == 0x29B1

ok = [
    "HELLO|1|0a1b2c3d|Studio|182|1790000000",
    "HI|1|0.1.0|0|5eed0001",
    "SNAP|3|12",
    "SUM|1|4|3|1",
    "PRJ|p1abcde|flipdeck|main|c|0|0|3000|r|0",
    "PRJ|p2abcde|interlockd|feature/x|d|2|-|0|-|1",
    "SVC|s0a1b2c|Vite|5173|flipdeck|1789997720",
    "AGT|g0a1b2c|Claude Code|flipdeck|r|1789990000",
    "ATN|t00a1b2|e|flipdeck|Production deploy failed",
    "EVT|e00a1b2|s|23:42|flipdeck|Production deployment is live",
    "ACT|s0a1b2c|a0zz9k1|STOP|dc|",
    "ACT|p1abcde|a0000z1|OPEN||",
    "END|3",
    "MAC|Studio|25|70|81|1|1|1789000000",
    "ALR|t00a1b2|e|flipdeck|Production deploy failed|Type error in app/page.tsx",
    "RES|12|1|Opened in Cursor",
    "REQ|12|a0zz9k1|3",
    "PING|3|1790000005",
    "PONG|3",
    "SYNC|0",
    "SEEN|t00a1b2",
    "BYE|quit",
    "FUTURE|unknown|types|still|decode",
]

bad = [
    ("badChecksum", "PING|3|1790000005*0000"),
    ("malformed", "PING|3|1790000005"),
    ("malformed", "PING|3*12G4"),
    ("malformed", frame("ping|1")),
    ("malformed", frame("")),
    ("malformed", "PING|1*ABC"),
    ("nonPrintable", "PING|\t1*0000"),
    ("tooLong", frame("EVT|" + "x" * 240)),
]

lines = [
    "# FDP/1 golden vectors. Generated by flipper/tools/gen_vectors.py; do not edit by hand.",
    "# OK <frame>            must decode, and re-encode to exactly the same bytes",
    "# BAD <reason> <line>   must be rejected with that reason",
]
lines += [f"OK {frame(p)}" for p in ok]
lines += [f"BAD {reason} {line}" for reason, line in bad]
out = pathlib.Path(__file__).resolve().parents[2] / "docs" / "protocol-vectors.txt"
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out} ({len(ok)} ok, {len(bad)} bad)")
