[phases.setup]
nixPkgs = ["nodejs_20", "python311"]

[phases.install]
cmds = ["cd web && npm ci"]

[phases.build]
cmds = ["cd web && npm run build", "node scripts/prebuild-packs.js"]

[start]
cmd = "cd web && npm run start"
